apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsdemo
spec:
  selector:
    matchLabels:
      app: jsdemo
  replicas: 2
  template:
    metadata:
      labels:
        app: jsdemo
    spec:
      containers:
      - name: jsdemo
        image: thenjdevopsguy/jsappturbo:latest
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: jsdemo
  labels:
    app: jsdemo
spec:
  type: LoadBalancer
  selector:
    app: jsdemo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
